### ISSUE TITLE
No "Remote logon" box on startup. 

### ISSUE THREAD

**Issue by MikefletenTrainee** [ArcticaProject/arctica-greeter#10]
When I start into Arctica-greeter, I don't get the Remote login box. I have to wait until i get an Internet connection, and then click on the Ubuntu icon to change desktop and go back.

**Comment by sunweaver** [comment]
Confirmed.

My way of getting the remote logon box is to re-connect the network in the nm-applet icon in the greeter (not in a local desktop session).

Nasty issue, will look into it soonish.

**Comment by sunweaver** [comment]
Might be related to #6 and https://github.com/ArcticaProject/remote-logon-service/commit/71e55e0f6cb1c949656441ee4f90585590efc68f
