### ISSUE TITLE
Is it possible to build the greeter without support for remote session?

### ISSUE THREAD

**Issue by DidierSpaier** [ArcticaProject/arctica-greeter#102]
I would like to replace in the Slint distribution that I maintain the gtk  lightdm greeter by the Arctica greeter.

However the target users barely need a remote graphical login, and not providing it would minimize the dependencies, especially those pulled by libpam-freerdp2.

**Comment by sunweaver** [comment]
@DidierSpaier Unfortunately not, patches welcome.

**Comment by DidierSpaier** [comment]
> @DidierSpaier Unfortunately not, patches welcome.

Thanks for answering. I will ship the slick greeter instead then, not having the coding skills needed to contribute. I don't think that makes a big difference wrt features, but the remote login. Is this right?

**Comment by Ionic** [comment]
You can pick my patch off the RPM packaging: https://build.opensuse.org/package/view_file/home:Ionic:branches:X11:Unity/arctica-greeter/arctica-greeter-disable-remote-logon.patch?expand=1

Note: often requires a bit of refactoring, but that's really not terribly difficult to do.

**Comment by DidierSpaier** [comment]
> You can pick my patch off the RPM packaging: https://build.opensuse.org/package/view_file/home:Ionic:branches:X11:Unity/arctica-greeter/arctica-greeter-disable-remote-logon.patch?expand=1
> 
> Note: often requires a bit of refactoring, but that's really not terribly difficult to do.

Thanks for the hint, will try to apply these patches.

**Comment by sunweaver** [comment]
@Ionic: It would be nice to refactor them into build time options.

**Comment by sunweaver** [comment]
> > @DidierSpaier Unfortunately not, patches welcome.
> 
> Thanks for answering. I will ship the slick greeter instead then, not having the coding skills needed to contribute. I don't think that makes a big difference wrt features, but the remote login. Is this right?

Slick greeter uses internal indicators, Arctica Greeter uses Ayatana Indicators. While this is another dependency bulk, the Ayatana Indicators offer a bridge between greeter and session (if the session uses those Ayatana Indicators, too). E.g. audio settings, bluetooth settings, display settings, etc. get communicated between greeter and session and vice versa.

**Comment by Ionic** [comment]
I just needed a quick way to disable this since we don't have the necessary dependencies (PAM modules), but I agree that it's probably good to have a way of disabling the remote logon feature completely if not needed in a convenient way, although that's the first request regarding this I've ever seen.

**Comment by DidierSpaier** [comment]
As it happened I had already packaged the ayatana indicators and applying the patch from Ionic succeeded.

Unfortunately the build failed, probably because of a versions mismatch between dependencies. I  attach the build log, FWIW.
[arctica_build.log](https://github.com/ArcticaProject/arctica-greeter/files/14057714/arctica_build.log)
But TBH I am not sure that for my use case the added payload of the ayatana packages (and the associated maintenance, considering that I maintain Slint alone) be worth using arctica rather than slick...

**Comment by Ionic** [comment]
0.99.3.0 is pretty old by now and contains a check for GTK 4 which can't be disabled. Since the build machine has GTK 4 development files installed, they are picked up and GTK 4 support is enabled, but that's currently broken anyway.

Update to the newest version - GTK 4 is disabled by default there.

**Comment by DidierSpaier** [comment]
Thanks for the hint. Build succeeded this time. Now I have to see if that works :)

**Comment by DidierSpaier** [comment]
It works. Thanks all.
