### ISSUE TITLE
Arctica-greeter Resolution bug

### ISSUE THREAD

**Issue by MikefletenTrainee** [ArcticaProject/arctica-greeter#11]
If you go in and change the resolution from Arctica-greeter on the remote desktop it will keep using the wrong resolution. It needs the "-g fullscreen" command.

**Comment by sunweaver** [comment]
Please: Define "If you go in..." (wherein?).

How do you change the resolution???

I guess, you reference using "-g fullscreen" as pyhoca-cli command line option.
