### ISSUE TITLE
Don't block shutdown

### ISSUE THREAD

**Issue by alkisg** [ArcticaProject/arctica-greeter#39]
Test case: on arctica-greeter, press the "poweroff" computer button (=ACPI shutdown). The attached suspend/reboot/shutdown dialog will shown forever, making graceful remote shutdowns impossible.

On the other hand, all other greeters that I've tested show a countdown of e.g. 60 seconds, honoring the shutdown event at the end of the countdown.
Please do the same!

The same issue also affects VirtualBox VMs, Proxmox servers (the MATE VMs block the server reboot) etc.

![VirtualBox_jammy-mate_23_10_2022_20_37_09](https://user-images.githubusercontent.com/88025/197407013-116023af-67cd-4267-ab75-d7fb37ce68ae.png)

**Comment by sunweaver** [comment]
@alkisg Thanks for this. I also stumbled over this recently. Will add some timeout.
