### ISSUE TITLE
test mode broken since 32d28d7bf2646fc7a0008937034246fcc96dbc8a

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/arctica-greeter#42]
@Ionic: test mode cannot be triggered via /usr/sbin/arctica-greeter --test-mode anymore since 32d28d7bf2646fc7a0008937034246fcc96dbc8a. Can you amend that? Thanks.

**Comment by Ionic** [comment]
Okay, will check that. I've always been using `--test-mode` and it worked for me, but maybe I've messed the patch up or didn't understand what it's supposed to do. What should it do in order to "work" correctly?

**Comment by sunweaver** [comment]
See attached two stderr logs of the command ``/usr/sbin/arctica-greeter --test-mode``. The version 0.99.1.5 works well, the version 0.99.2.0 hangs at some point and does not come up.

[arctica-greeter-test-mode-0.99.1.5.log](https://github.com/ArcticaProject/arctica-greeter/files/10676796/arctica-greeter-test-mode-0.99.1.5.log)
[arctica-greeter-test-mode-0.99.2.0.log](https://github.com/ArcticaProject/arctica-greeter/files/10676798/arctica-greeter-test-mode-0.99.2.0.log)
