### ISSUE TITLE
Testmode fixes now block construction while in GLib.Bus.watch_name()

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/arctica-greeter#44]
@Ionic: With the latest fix for ``arctica-greeter --test-mode`` the greeter doesn't come up anymore when running as display manager via LightDM.

I added some extra debug messages and the code never reaches ``debug ("At end of ArcticaGreeter.construct().");``.

@Ionic: Have you tested your change with arctica-greeter running as display manager? If not, please revisit. Thanks.

```
diff --git a/src/arctica-greeter.vala b/src/arctica-greeter.vala
index 322f7e3..10878f1 100644
--- a/src/arctica-greeter.vala
+++ b/src/arctica-greeter.vala
@@ -123,6 +123,9 @@ public class ArcticaGreeter : Object
                                                     debug ("xsettings is ready");
                                                     continue_init = true;
                                                 }
+                                                else {
+                                                    debug ("connected settings-daemon plugin '%s'", name);
+                                                }
                                             }
                                         );
                                     }
@@ -155,10 +158,12 @@ public class ArcticaGreeter : Object
              */
             continue_init = true;
         }
+        debug ("At end of ArcticaGreeter.construct().");
     }
 
     public override void constructed ()
     {
+        debug ("Nearly done with constructing SingleInstance class object ArcticaGreeter.");
         if (continue_init)
         {
             xsettings_ready ();
@@ -166,6 +171,7 @@ public class ArcticaGreeter : Object
 
         /* Chain up - actually necessary. */
         base.constructed ();
+        debug ("Fully done with constructing SingleInstance class object ArcticaGreeter.");
     }
 
     /*
```

**Comment by Ionic** [comment]
Oh, crap, no, I was too happy about fixing the standalone `--test-mode` that I didn't bother to check running it via lightdm. :(

**Comment by sunweaver** [comment]
IMHO, we need to move the DBus watch_name call out of the constructor into a run() method (or similar) and expect that watch_name call to block everything until the msd gets killed, so it basically is a pre-step into executing the mainloop.

**Comment by Ionic** [comment]
But we can't do  this unless the start multithreading AG. That's probably a lot of effort for little gain, especially since everything else is written asynchronously just using one process/thread. I was happy to find the `constructed` function later on, couldn't really explain why it is hanging now, especially since I haven't changed any code in the LightDM context.

**Comment by sunweaver** [comment]
The cause why it hangs now is that it never leaves the watch_name() call, only if you trigger a signal from within it. But as we don't trigger xsettings_ready() anymore, we rely on construct() being fully finished, which never happens.

**Comment by sunweaver** [comment]
Resolved via https://github.com/ArcticaProject/arctica-greeter/commit/2c2cc676770044aafb61db0cef306a98950e0ac3 (and follow-up commits).
