### ISSUE TITLE
Failing to compile Arctica Greeter 

### ISSUE THREAD

**Issue by rokas-ju** [ArcticaProject/arctica-greeter#7]
Hello everyone,
I have followed the guide on how to install the Arctica Greeter. I followed the guide, did a fresh install, everything seemed to be working fine until I got to the point where I had to use the debuild command on all 5 folders. I have managed to debuild all of them except for the arctica-greeter folder. I installed the additional dependencies that weren't listed on the guide, but after doing that, I got even more errors when trying to debuild.

`
dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package arctica-greeter
dpkg-buildpackage: source version 0.99.0.1-0
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
 dpkg-source --before-build arctica-greeter
dpkg-buildpackage: host architecture amd64
 fakeroot debian/rules clean
dh clean --with autoreconf --fail-missing
   dh_testdir -O--fail-missing
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/root/greeter/arctica-greeter'
dh_auto_clean
    make -j1 distclean
make[2]: Entering directory '/root/greeter/arctica-greeter'
Making distclean in src
make[3]: Entering directory '/root/greeter/arctica-greeter/src'
test -z "logo-generator" || rm -f logo-generator
test -z "arctica-greeter" || rm -f arctica-greeter
rm -f *.o
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
test -z "Makefile.in" || rm -f Makefile.in
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ./.deps
rm -f Makefile
make[3]: Leaving directory '/root/greeter/arctica-greeter/src'
Making distclean in data
make[3]: Entering directory '/root/greeter/arctica-greeter/data'
rm -f org.ArcticaProject.arctica-greeter.gschema.valid 
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
test -z "50-arctica-greeter.conf 50-arctica-guest-wrapper.conf arctica-greeter.desktop arctica-guest-session-startup.desktop Makefile.in logo.png" || rm -f 50-arctica-greeter.conf 50-arctica-guest-wrapper.conf arctica-greeter.desktop arctica-guest-session-startup.desktop Makefile.in logo.png
rm -f Makefile
make[3]: Leaving directory '/root/greeter/arctica-greeter/data'
Making distclean in po
make[3]: Entering directory '/root/greeter/arctica-greeter/po'
rm -f *.pox arctica-greeter.pot *.old.po cat-id-tbl.tmp
rm -f .intltool-merge-cache
rm -f Makefile Makefile.in POTFILES stamp-it
rm -f *.mo *.msg *.cat *.cat.m *.gmo
make[3]: Leaving directory '/root/greeter/arctica-greeter/po'
Making distclean in tests
make[3]: Entering directory '/root/greeter/arctica-greeter/tests'
test -z "arctica-greeter-test" || rm -f arctica-greeter-test
test -z "test.c test-list.c test-main-window.c menubar.c arctica-greeter.c flat-button.c toggle-box.c user-list.c greeter-list.c remote-logon-service.c background.c email-autocompleter.c config.vapi fixes.vapi cairo-utils.c animate-timer.c indicator.vapi fadable.c fadable-box.c dash-box.c user-prompt-box.c fading-label.c cached-image.c dash-entry.c dash-button.c prompt-box.c session-list.c main-window.c list-stack.c settings.c shutdown-dialog.c" || rm -f test.c test-list.c test-main-window.c menubar.c arctica-greeter.c flat-button.c toggle-box.c user-list.c greeter-list.c remote-logon-service.c background.c email-autocompleter.c config.vapi fixes.vapi cairo-utils.c animate-timer.c indicator.vapi fadable.c fadable-box.c dash-box.c user-prompt-box.c fading-label.c cached-image.c dash-entry.c dash-button.c prompt-box.c session-list.c main-window.c list-stack.c settings.c shutdown-dialog.c
rm -f *.o
rm -f ../src/*.o
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f ../src/.deps/.dirstamp
rm -f ../src/.dirstamp
test -z "Makefile.in" || rm -f Makefile.in
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ../src/.deps ./.deps
rm -f Makefile
make[3]: Leaving directory '/root/greeter/arctica-greeter/tests'
make[3]: Entering directory '/root/greeter/arctica-greeter'
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
test -z "Makefile.in aclocal.m4 arctica-guest-account-script compile configure config.h.in config.h depcomp gtk-doc.make install-sh missing mkinstalldirs omf.make xmldocs.make po/Makefile.in.in" || rm -f Makefile.in aclocal.m4 arctica-guest-account-script compile configure config.h.in config.h depcomp gtk-doc.make install-sh missing mkinstalldirs omf.make xmldocs.make po/Makefile.in.in
rm -f config.h stamp-h1
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
make[3]: Leaving directory '/root/greeter/arctica-greeter'
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
make[2]: Leaving directory '/root/greeter/arctica-greeter'
if [ -e po/arctica-greeter.pot.bak ]; then \
    mv -f po/arctica-greeter.pot.bak po/arctica-greeter.pot; \
fi
rm -f src/arctica_greeter_vala.stamp
rm -f src/logo_generator_vala.stamp
rm -f tests/arctica_greeter_test_vala.stamp
rm -f src/*.c
rm -f tests/*.c
rm -f debian/theme-debian-logo.png
make[1]: Leaving directory '/root/greeter/arctica-greeter'
   dh_autoreconf_clean -O--fail-missing
   dh_clean -O--fail-missing
 dpkg-source -b arctica-greeter
dpkg-source: warning: source directory 'arctica-greeter' is not <sourcepackage>-<upstreamversion> 'arctica-greeter-0.99.0.1'
dpkg-source: info: using source format '1.0'
dpkg-source: info: building arctica-greeter in arctica-greeter_0.99.0.1-0.tar.gz
dpkg-source: info: building arctica-greeter in arctica-greeter_0.99.0.1-0.dsc
 debian/rules build
dh build --with autoreconf --fail-missing
   dh_testdir -O--fail-missing
   dh_update_autotools_config -O--fail-missing
   debian/rules override_dh_autoreconf
make[1]: Entering directory '/root/greeter/arctica-greeter'
if [ ! -e po/arctica-greeter.pot.bak ]; then \
    cp po/arctica-greeter.pot po/arctica-greeter.pot.bak; \
fi
NOCONFIGURE=1 dh_autoreconf ./autogen.sh
/usr/bin/mate-autogen
checking for autoconf >= 2.53...
  testing autoconf2.50... not found.
  testing autoconf... found 2.69
checking for automake >= 1.7...
  testing automake-1.15... found 1.15
checking for intltool >= 0.25...
  testing intltoolize... found 0.51.0
checking for pkg-config >= 0.14.0...
  testing pkg-config... found 0.29.1
checking for mate-common >= 1.1.0...
  testing mate-doc-common... found 1.12.0
Checking for required M4 macros...
Checking for forbidden M4 macros...
Processing ./configure.ac
Running mate-doc-common...
Running intltoolize...
Running autoreconf...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --warnings=no-portability 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
autoreconf: running: /usr/bin/autoheader --force --warnings=no-portability
autoreconf: running: automake --add-missing --copy --force-missing --warnings=no-portability
configure.ac:8: installing './compile'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
Makefile.am: installing './INSTALL'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
Skipping configure process.
make[1]: Leaving directory '/root/greeter/arctica-greeter'
   dh_auto_configure -O--fail-missing
    ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for valac... /usr/bin/valac
checking whether /usr/bin/valac is at least version 0.24.0... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for ARCTICA_GREETER... yes
checking for valgrind... valgrind --trace-children=yes --num-callers=256
checking whether NLS is requested... yes
checking for intltool >= 0.35.0... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.22.1
checking for XML::Parser... ok
checking for GTK_3_20_0... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating data/Makefile
config.status: creating po/Makefile.in
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing po/stamp-it commands
   debian/rules override_dh_auto_build
make[1]: Entering directory '/root/greeter/arctica-greeter'
dh_auto_build
    make -j1
make[2]: Entering directory '/root/greeter/arctica-greeter'
make  all-recursive
make[3]: Entering directory '/root/greeter/arctica-greeter'
Making all in src
make[4]: Entering directory '/root/greeter/arctica-greeter/src'
rm -f logo_generator_vala.stamp && echo stamp > logo_generator_vala.stamp-t
CDPATH="${ZSH_VERSION+.}:" && cd . && /usr/bin/valac  --debug --pkg posix --pkg gtk+-3.0 --pkg gdk-x11-3.0 --pkg gio-unix-2.0 --pkg x11 --pkg liblightdm-gobject-1 --pkg libcanberra --pkg gio-2.0 --pkg pixman-1 --target-glib 2.32  -C logo-generator.vala
mv -f logo_generator_vala.stamp-t logo_generator_vala.stamp
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -D_REENTRANT -I/usr/include/gtk-3.0 -I/usr/include/libayatana-ido3-0.4 -I/usr/include/libayatana-indicator3-0.4 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/lightdm-gobject-1 -I/usr/include/gio-unix-2.0/ -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/freetype2 -I/usr/include/pixman-1 -w -DGETTEXT_PACKAGE=\"arctica-greeter\" -DLOCALEDIR=\""/usr/share/locale"\" -DVERSION=\"0.99.0.1\" -DPKGDATADIR=\""/usr/share/arctica-greeter"\" -DINDICATORDIR=\""/usr/lib/ayatana-indicators3/7/"\" -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c -o logo_generator-logo-generator.o `test -f 'logo-generator.c' || echo './'`logo-generator.c
gcc -pthread -D_REENTRANT -I/usr/include/gtk-3.0 -I/usr/include/libayatana-ido3-0.4 -I/usr/include/libayatana-indicator3-0.4 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/lightdm-gobject-1 -I/usr/include/gio-unix-2.0/ -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/freetype2 -I/usr/include/pixman-1 -w -DGETTEXT_PACKAGE=\"arctica-greeter\" -DLOCALEDIR=\""/usr/share/locale"\" -DVERSION=\"0.99.0.1\" -DPKGDATADIR=\""/usr/share/arctica-greeter"\" -DINDICATORDIR=\""/usr/lib/ayatana-indicators3/7/"\" -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -Wl,-Bsymbolic-functions -Wl,-z,relro -o logo-generator logo_generator-logo-generator.o -lgdk-3 -layatana-ido3-0.4 -layatana-indicator3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -llightdm-gobject-1 -lcairo -lfreetype -lcanberra -lpixman-1 -lX11 -lXext -lm 
rm -f arctica_greeter_vala.stamp && echo stamp > arctica_greeter_vala.stamp-t
CDPATH="${ZSH_VERSION+.}:" && cd . && /usr/bin/valac  --debug --pkg posix --pkg gtk+-3.0 --pkg gdk-x11-3.0 --pkg gio-unix-2.0 --pkg x11 --pkg liblightdm-gobject-1 --pkg libcanberra --pkg gio-2.0 --pkg pixman-1 --target-glib 2.32  -C config.vapi fixes.vapi indicator.vapi xsync.vapi animate-timer.vala background.vala cached-image.vala cairo-utils.vala email-autocompleter.vala dash-box.vala dash-button.vala dash-entry.vala fadable.vala fadable-box.vala fading-label.vala flat-button.vala greeter-list.vala idle-monitor.vala list-stack.vala main-window.vala menu.vala menubar.vala prompt-box.vala session-list.vala remote-logon-service.vala settings.vala settings-daemon.vala shutdown-dialog.vala toggle-box.vala arctica-greeter.vala user-list.vala user-prompt-box.vala
main-window.vala:216.9-216.19: error: The type name `Gdk.Monitor' could not be found
        Gdk.Monitor primary = display.get_primary_monitor();
        ^^^^^^^^^^^
main-window.vala:225.13-225.23: error: The type name `Gdk.Monitor' could not be found
            Gdk.Monitor monitor = display.get_monitor(i);
            ^^^^^^^^^^^
main-window.vala:249.9-249.19: error: The type name `Gdk.Monitor' could not be found
        Gdk.Monitor mon0;
        ^^^^^^^^^^^
main-window.vala:256.13-256.23: error: The type name `Gdk.Monitor' could not be found
            Gdk.Monitor mon1;
            ^^^^^^^^^^^
main-window.vala:54.9-54.26: error: The type name `Gdk.DrawingContext' could not be found
        Gdk.DrawingContext background_context;
        ^^^^^^^^^^^^^^^^^^
Compilation failed: 5 error(s), 0 warning(s)
Makefile:1090: recipe for target 'arctica_greeter_vala.stamp' failed
make[4]: *** [arctica_greeter_vala.stamp] Error 1
make[4]: Leaving directory '/root/greeter/arctica-greeter/src'
Makefile:510: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/root/greeter/arctica-greeter'
Makefile:381: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/root/greeter/arctica-greeter'
dh_auto_build: make -j1 returned exit code 2
debian/rules:20: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/root/greeter/arctica-greeter'
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
`
Is there something I am missing? Any kind of help is greatly appreciated!

**Comment by sunweaver** [comment]
Hi

On Saturday, August 19, 2017, grind321 wrote:
> Hello everyone,
> I have followed the guide on how to install the Arctica Greeter. I followed the guide, did a fresh install, everything seemed to be working fine until I got to the point where I had to use the debuild command on all 5 folders. I have managed to debuild all of them except for the arctica-greeter folder. I installed the additional dependencies that weren't listed on the guide, but after doing that, I got even more errors when trying to debuild.
> Compilation failed: 5 error(s), 0 warning(s) Makefile:1090: recipe for target 'arctica_greeter_vala.stamp' failed make[4]: *** [arctica_greeter_vala.stamp] Error 1 make[4]: Leaving directory '/root/greeter/arctica-greeter/src' Makefile:510: recipe for target 'all-recursive' failed make[3]: *** [all-recursive] Error 1 make[3]: Leaving directory '/root/greeter/arctica-greeter' Makefile:381: recipe for target 'all' failed make[2]: *** [all] Error 2 make[2]: Leaving directory '/root/greeter/arctica-greeter' dh_auto_build: make -j1 returned exit code 2 debian/rules:20: recipe for target 'override_dh_auto_build' failed make[1]: *** [override_dh_auto_build] Error 2 make[1]: Leaving directory '/root/greeter/arctica-greeter' debian/rules:6: recipe for target 'build' failed make: *** [build] Error 2 dpkg-buildpackage: error: debian/rules build gave error exit status 2 debuild: fatal error at line 1376: dpkg-buildpackage -rfakeroot -D -us -uc failed
> Is there something I am missing? Any kind of help is greatly appreciated! 

The attached build log tail does not provide info on the actual error.

My suspicion is that you try to build on Ubuntu trusty which is not supported anymore. Docs need to be adapted. Use Debian 9 or Ubuntu 16.04.

Mike

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by rokas-ju** [comment]
Strange, but I am using 16.04. I'll re-edit with the full log.

**Comment by sunweaver** [comment]
@grind321: please note that recent versions of arctica-greeter require libpam-x2go-dev and libpam-freerd2p-dev. (I need to make that optional, but currently those are hard build dependencies).

I close this issue now, as builds are definitely working here. Please reopen, if you can back to me with more concrete info / build logs.
